from django.conf import settings
from django.db import models

class User_reg(models.Model):
    Roll_Number = models.CharField(max_length=10,default='',primary_key=True)
    Full_Name = models.CharField(max_length=100,default='')
    Pursuing_Degree = models.CharField(max_length=50,default='')
    Department = models.CharField(max_length=50,default='')
    Contact = models.CharField(max_length=20,default='')
    Alternate_Contact = models.CharField(max_length=20,default='')
    Email = models.EmailField(max_length=254,default='')
    Alternate_Email = models.EmailField(max_length=254,default='')
    DOB = models.CharField(max_length=20,default='')
    Gender = models.CharField(max_length=10,default='')
    Marital_Status = models.CharField(max_length=20,default='')
    #family_details
    fstrength = models.IntegerField(default=0)
    famem = models.CharField(max_length=255,default='0')
    mname = models.CharField(max_length=100,default='')
    mcontact = models.CharField(max_length=15,default='')
    moccupation = models.CharField(max_length=100,default='')
    fname = models.CharField(max_length=100,default='')
    fcon = models.CharField(max_length=15,default='')
    foccupation = models.CharField(max_length=100,default='')
    sname = models.CharField(max_length=100,default='')
    scontact = models.CharField(max_length=15,default='')
    soccupation = models.CharField(max_length=100,default='')
    permanent_address = models.CharField(max_length=200,default='')
    current_address = models.CharField(max_length=200,default='')
    #work_agreement
    work_interest = models.CharField(max_length=200,default='')
    work_location = models.CharField(max_length=200,default='')
    sis = models.CharField(max_length=200,default='')
    #mand_docs
    aadhar_no = models.CharField(max_length=12, default='NA')
    pan_number = models.CharField(max_length=10, default='NA')
    linkedin_profile = models.CharField(max_length=255, default='NA')
    linkedin_link = models.URLField(max_length=255, default='NA')
    pursuing = models.CharField(max_length=50,default='NA')
    #schooling
    sslc_school = models.CharField(max_length=255, blank=True)
    sslc_school_address = models.TextField(blank=True)
    sslc_mark = models.TextField(blank=True, null=True)
    sslc_percentage = models.TextField(blank=True, null=True)
    sslc_year = models.TextField(blank=True, null=True)

    hsc_school = models.CharField(max_length=255, blank=True)
    hsc_school_address = models.TextField(blank=True)
    hsc_mark = models.TextField(blank=True, null=True)
    hsc_percentage = models.TextField(blank=True, null=True)
    hsc_year = models.TextField(blank=True, null=True)

    diploma_clg = models.CharField(max_length=255, blank=True)
    diploma_clg_address = models.TextField(blank=True)
    diploma_percentage = models.TextField(blank=True, null=True)
    diploma_year = models.TextField(blank=True, null=True)
    #ug_details
    gap_year = models.CharField(max_length=255, blank=True)
    ug_department = models.CharField(max_length=255, blank=True)
    ug_hod = models.CharField(max_length=255, blank=True)
    ug_hod_no = models.CharField(max_length=255, blank=True)
    ug_seed = models.CharField(max_length=255, blank=True)
    ug_seed_no = models.CharField(max_length=255, blank=True)
    ug_seed_mail = models.EmailField(max_length=255, blank=True)
    ug_percentage = models.FloatField(blank=True, null=True,default=0)
    active_ug_arrears_count = models.IntegerField(blank=True, null=True,default=0)
    ug_arrears_count = models.IntegerField(blank=True, null=True,default=0)
    ug_intern_period = models.CharField(max_length=255, blank=True)
    #pg_details
    pg_department = models.CharField(max_length=255, blank=True)
    pg_hod = models.CharField(max_length=255, blank=True)
    pg_hod_no = models.CharField(max_length=255, blank=True)
    pg_seed = models.CharField(max_length=255, blank=True)
    pg_seed_no = models.CharField(max_length=255, blank=True)
    pg_seed_mail = models.EmailField(max_length=255, blank=True)
    pg_percentage = models.IntegerField(blank=True, null=True,default=0)
    active_pg_arrears_count = models.IntegerField(blank=True, null=True,default=0)
    pg_arrears_count = models.IntegerField(blank=True, null=True,default=0)
    pg_intern_period = models.CharField(max_length=255, blank=True)
    ex_ug_university = models.CharField(max_length=255, blank=True)
    ex_ug_college = models.CharField(max_length=255, blank=True)
    ex_ug_college_address = models.CharField(max_length=255, blank=True)
    ex_ug_department = models.CharField(max_length=255, blank=True)
    ex_ug_percentage = models.IntegerField(blank=True, null=True,default=0)
    ex_ug_internship_company = models.CharField(max_length=255, blank=True)
    ex_ug_internship_period = models.CharField(max_length=255, blank=True)
    ex_ug_work_company = models.CharField(max_length=255, blank=True)
    ex_ug_work_period = models.CharField(max_length=255, blank=True)
    ex_ug_work_uan = models.CharField(max_length=255, blank=True)
    #others
    why_placements=models.TextField(max_length=500,default='')
    about_yourself = models.TextField(max_length=500,default='')
    languages_known = models.CharField(max_length=150,default='')
    prog_languages = models.CharField(max_length=300,default='')

class intern_db(models.Model):
    reg_no = models.CharField(max_length=50, blank=True, primary_key=True)
    password = models.CharField(max_length=150, blank=True)
    name = models.CharField(max_length=150, blank=True,unique=True)
    placed_company = models.CharField(max_length=200, blank=True, default='NA')
    intern_start = models.CharField(max_length=150, blank=True)
    intern_end = models.CharField(max_length=150, blank=True)

class Intern_atn(models.Model):
    reg_no = models.CharField(max_length=50, blank=True)
    #name = models.ForeignKey(intern_db, on_delete=models.CASCADE)
    Date = models.CharField(max_length=50, blank=True)
    Intime = models.CharField(max_length=50, blank=True)
    Outtime = models.CharField(max_length=50, blank=True)
    locationIn = models.CharField(max_length=50, blank=True)
    locationOut = models.CharField(max_length=50, blank=True)

    class Meta:
        unique_together = ('reg_no', 'Date')

'''class Student_DB(models.Model):
    reg_no = models.CharField(max_length=50, blank=True)
    name = models.CharField(max_length=150, blank=True)
    department = models.CharField(max_length=150, blank=True)
    year = models.CharField(max_length=10, blank=True)
    profile_status = models.CharField(max_length=50, blank=True)'''
