# Generated by Django 4.1.7 on 2023-04-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superlee', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intern_atn',
            unique_together={('reg_no', 'Date')},
        ),
    ]
