# Generated by Django 4.1.7 on 2023-04-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlee', '0003_alter_intern_atn_date_alter_intern_atn_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern_atn',
            name='name',
        ),
        migrations.AddField(
            model_name='intern_db',
            name='intern_end',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='intern_db',
            name='intern_start',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
