# Generated by Django 4.1.7 on 2023-04-26 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superlee', '0004_remove_intern_atn_name_intern_db_intern_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern_atn',
            name='name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='superlee.intern_db'),
            preserve_default=False,
        ),
    ]
