# Generated by Django 4.1.7 on 2023-04-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superlee', '0006_remove_intern_atn_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intern_atn',
            unique_together=set(),
        ),
    ]
